version: "3"
services:
    hie-docker:
        build:
            context: ./hie-docker
        volumes:
            - ./:/tmp/project_root
        stdin_open: true
        entrypoint: sh

    docker-langserver:
        image: rcjsuen/docker-langserver
        volumes:
            - ./:/tmp/project_root
        stdin_open: true
        entrypoint: sh

    main:
        build:
            context: ./neovim-docker
            args:
                cmds:
                    ${COMPOSE_PROJECT_NAME}_hie-docker_1:hie-wrapper
                    ${COMPOSE_PROJECT_NAME}_hie-docker_1:stack
                    ${COMPOSE_PROJECT_NAME}_docker-langserver_1:/docker-langserver/bin/docker-langserver
        volumes:
            - ./:/tmp/project_root
            - /var/run/docker.sock:/var/run/docker.sock
            - ./coc-settings.json:/home/user/.config/nvim/coc-settings.json
        stdin_open: true
        working_dir: /tmp/project_root
