version: "3.4"

services:
    neovim:
        volumes:
            - ./coc-settings.json:/root/.config/nvim/coc-settings.json

    haskell:
        # Prevent ETXTBSY in VirtualBox
        volumes:
            - /root/project_root/.stack-work
        command: sh -c 'sudo chown `id -u`:`id -g` .stack-work && eval $${PREPARE_COMMAND} && while sleep 1000; do :; done'
