version: "3.4"

x-common-options: &common-options
    depends_on:
        - docker
    user: ${UID}:${GID}
    environment:
        - "PREPARE_COMMAND=find /root/shared_bin/* | xargs -I {} basename {} | xargs -I {} sh -c 'command -v {} || sudo cp /root/shared_bin/{} /usr/local/bin/{}'"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./:/root/project_root
        - shared_bin:/root/shared_bin
        - tmp:/tmp
    working_dir: /root/project_root
    command: sh -c 'eval $${PREPARE_COMMAND} && while sleep 1000; do :; done'

services:
    scripts:
        image: bash
        volumes:
            - shared_bin:/scripts
            - ./generate_docker_cmd.sh:/generate_docker_cmd.sh
        command: >
            /generate_docker_cmd.sh /scripts
            nvim@${COMPOSE_PROJECT_NAME}_neovim_1
            git@${COMPOSE_PROJECT_NAME}_git_1
            stack@${COMPOSE_PROJECT_NAME}_haskell_1
            haskell-language-server-wrapper@${COMPOSE_PROJECT_NAME}_haskell_1

    docker:
        build:
            context: ./docker-docker
        depends_on:
            - scripts
        volumes:
            - shared_bin:/tmp/shared_bin
        command: sh -c "cp -f `which docker` /tmp/shared_bin/docker && while sleep 1000; do :; done"

    neovim:
        build:
            context: ./neovim-docker
            args:
                EXTRA_COC_PLUGINS: coc-docker
        <<: *common-options

    git:
        build:
            context: ./git-docker
        <<: *common-options

    haskell:
        build:
            context: ./hls-docker
        <<: *common-options

volumes:
    shared_bin:
    tmp:
