name:                haskell-template
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://k-ishigaki.github.io/
license:             MIT
author:              Kazuki Ishigaki
maintainer:          gakia5310027@gmail.com
copyright:           2020 Kazuki Ishigaki
category:            Command Line Tool
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - conduit
  - conduit-extra
  - text
  - mtl

executables:
  haskell-template:
    source-dirs:      src
    main:             Main.hs
